<a href="https://colab.research.google.com/github/olumichael1/Data-science-training/blob/main/assignment_2_on_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
print("Numpy version: " + np.version.version)

Numpy version: 1.19.5


In [7]:
print("pandas version: " + pd.__version__)

pandas version: 1.1.5


In [9]:
#creating a numpy array from a list

sample = np.array([1,2,3,4,5,6])

print(sample)

[1 2 3 4 5 6]


In [10]:
type(sample)

numpy.ndarray

Creating a matrix from a list


In [11]:
mymatrix = [[1,3,5],[0,3,7],[23,9,17]]
mymatrix

[[1, 3, 5], [0, 3, 7], [23, 9, 17]]

Convert a matrix int Numpy array

In [13]:
numpy_array = np.array(mymatrix)

print(numpy_array)

[[ 1  3  5]
 [ 0  3  7]
 [23  9 17]]


Check if the data type are NumPy array

In [14]:
type(numpy_array)

numpy.ndarray

Convert the NumPy array into a Pandas DataFrame

In [26]:
df_from_array = pd.DataFrame(numpy_array)
df_from_array

0  1   2
0   1  3   5
1   0  3   7
2  23  9  17