Create two different array( x and y) from a list

In [18]:
#creating Array x and y
import numpy as np

arr_x = np.array([[11,21,23,27],[2,17,0,5]])       #array x create

arr_y = np.array([[10,12,16,18],[3,9,1,15]])       #array y create

print("Array x")
print(arr_x)

print ("and")

print("Array y")
print(arr_y)

Array x
[[11 21 23 27]
 [ 2 17  0  5]]
and
Array y
[[10 12 16 18]
 [ 3  9  1 15]]


Addition of array, x and y. Print the result

In [13]:
# addition of array_x and array_y

print("Direct Addition")

print (arr_x + arr_y)

Direct Addition
[[21 33 39 45]
 [ 5 26  1 20]]


Subtract array, x from y. Print the result

In [15]:
# subtraction of array_x from array_y

print("Direct subtraction")
print (arr_x - arr_y)

Direct subtraction
[[  1   9   7   9]
 [ -1   8  -1 -10]]


Multiply array, x by 5. Print the result.

In [16]:
# multiply array_x by 5

print("Direct multiplication")
print(arr_x * 5)                  # multiplying array x by 5

Direct multiplication
[[ 55 105 115 135]
 [ 10  85   0  25]]


Divide array, y and 10. Print the result.

In [17]:
# Dividing array y with 10

print("Direct division")
print(arr_y / 10)

Direct division
[[1.  1.2 1.6 1.8]
 [0.3 0.9 0.1 1.5]]
