Create two different array( x and y) from a list

In [1]:
#creating Array x and y
import numpy as np
import pandas as pd

arr_x = np.array([[11,21,23,27],[2,17,0,5]])       #array x create

arr_y = np.array([[10,12,16,18],[3,9,1,15]])       #array y create

print("Array x")
print(arr_x)

print ("and")

print("Array y")
print(arr_y)

Array x
[[11 21 23 27]
 [ 2 17  0  5]]
and
Array y
[[10 12 16 18]
 [ 3  9  1 15]]


Addition of array, x and y. Print the result

In [2]:
# addition of array_x and array_y

print("Direct Addition")

print (arr_x + arr_y)

Direct Addition
[[21 33 39 45]
 [ 5 26  1 20]]


Subtract array, x from y. Print the result

In [3]:
# subtraction of array_x from array_y

print("Direct subtraction")
print (arr_x - arr_y)

Direct subtraction
[[  1   9   7   9]
 [ -1   8  -1 -10]]


Multiply array, x by 5. Print the result.

In [4]:
# multiply array_x by 5

print("Direct multiplication")
print(arr_x * 5)                  # multiplying array x by 5

Direct multiplication
[[ 55 105 115 135]
 [ 10  85   0  25]]


Divide array, y and 10. Print the result.

In [5]:
# Dividing array y with 10

print("Direct division")
print(arr_y / 10)

Direct division
[[1.  1.2 1.6 1.8]
 [0.3 0.9 0.1 1.5]]


Create a Pandas DataFrame
Pandas DataFrame is a two-dimensional labeled data structure

In [6]:
#Creating from a list of lists
pet_info = [['Howard', 10, 'Goat'], ['Lucy', 4 , 'Fish'], ['Roco', 8, 'Lizard']]
pet_info

[['Howard', 10, 'Goat'], ['Lucy', 4, 'Fish'], ['Roco', 8, 'Lizard']]

In [7]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
index = ['A', 'B', 'C'])

(pet_df)

Name  Age    Type
A  Howard   10    Goat
B    Lucy    4    Fish
C    Roco    8  Lizard

In [8]:
pet_df['Name']

A    Howard
B      Lucy
C      Roco
Name: Name, dtype: object

In [9]:
pet_df['Age']

A    10
B     4
C     8
Name: Age, dtype: int64

Excercise 2! Print out the 'Type' of the columns in pet_df

In [10]:
pet_df['Type']

A      Goat
B      Fish
C    Lizard
Name: Type, dtype: object

In [11]:
type(pet_df)

pandas.core.frame.DataFrame

Excercise 3

1. Download the weight-height.csv dataset.
2. Read the dataset using pandas.
3. using pandas positioning to display the fifth datapoint.
4. Print a column from the dataset.

Download and importing csv to google colab

In [12]:
# download and importing csv to google colab

from google.colab import files
  
  
uploaded = files.upload()

Saving weight-height.csv to weight-height (2).csv


Reading of csv.dataset using pandas

In [14]:
#Reading of csv.dataset using pandas
import io


df = pd.read_csv(io.BytesIO(uploaded['weight-height.csv']))
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]


Using pandas positioning to display the fifth datapoint.

In [15]:
df[:6:1]   # using pandas positioning and display the fifth data point

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156

Print a column from the dataset.

In [17]:
import pandas

file = pandas.read_csv("weight-height.csv")   # print the header.column from the dataset
for columns in file.columns:
    print(columns)

Gender
Height
Weight
